server:
  port: 8065
  address: localhost

spring:
  application:
    name: SERVICE-DISCOVERY

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false
